name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup key
      - run: set -eu
      - run: mkdir "~/.ssh"
      - run: echo "$" > "~/.ssh/id_rsa.pub"
      - run: chmod 600 "~/.ssh/id_rsa.pub"
      # Build
      - run: npm ci
      - run: npm run build
      # Deploy
      - run: scp -r c:\Users\Alexey\PycharmProject\strana user@server:git@github.com:Edelweiss1304/strana.git