name: Run tests every 5 minutes
on:
  schedule:
    - cron: '30 8 * * *'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-selenium
        sudo apt-get update
        sudo apt-get install chromium-browser
    - name: Run tests
      run: pytest tests
