name: Run tests every 5 minutes
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable chromium-browser
        sudo python -m pip install --upgrade pip
        sudo pip install pytest pytest-selenium
    - name: Run tests
      run: pytest tests
