name: Тестовый запуск
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install Allure Commandline
        run: |
          curl -o allure-2.13.8.tgz -Ls https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.13.8/allure-commandline-2.13.8.tgz
          mkdir allure
          tar -zxvf allure-2.13.8.tgz -C allure
          echo "${{ github.workspace }}/allure/allure-2.13.8/bin" >> $GITHUB_PATH
      - name: Run tests with Allure
        run: python test_script.py
        continue-on-error: true















