name: Тестовый запуск брокер
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Prepare config
        run: |
          cat > connection_config.ini <<EOT
          [testit]
          url = https://testit.itstrana.site/
          privateToken = ${{ secrets.TMS_PRIVATE_TOKEN }}
          projectId = eefe44b2-3347-4e63-83e6-18614e869fe3
          configurationId = 659d9644-c5dc-4542-8aef-3858f219f8b6
          testRunId =
          testRunName = Test
          adapterMode = 2
          EOT

      - name: Test run for testit
        run: |
          pytest_output=$(pytest tests/test_broker.py)
          echo "${pytest_output}" > test_results.txt
          passed_tests=$(echo "${pytest_output}" | grep -c '===.*===')
          failed_tests=$(echo "${pytest_output}" | grep -E 'FAILED' | sed -E 's/.*::(test_[^\s]+).*/\1/' | tr '\n' ', ')
          echo "pytest_output=${pytest_output}" >> $GITHUB_ENV
          echo "Passed tests: ${passed_tests}"
          echo "Failed tests: ${failed_tests}"
          if [ -n "${failed_tests}" ]; then
            echo "Failed tests: ${failed_tests}" >> $GITHUB_ENV
          fi

      - name: Notify on Telegram
        if: always()
        env:
          TELEGRAM_BOT_TOKEN: 7034452771:AAGAEMKO3shKsPOu1FlSJxmJkQ2SUIbLYHE
          TELEGRAM_CHAT_ID: -4162914238
          FAILED_TESTS: ${{ env.FAILED_TESTS }}
        run: |
          TEXT="Результаты тестирования:"
          echo "Sending notification with text: ${TEXT}"
          if [ -n "${FAILED_TESTS}" ]; then
            failed_tests=$(grep -E '^[^=F]+' test_results.txt | sed 's/^  \([a-zA-Z0-9_]\+\) \.\.\. FAILED/\1/')
            TEXT="Тесты провалены: ${failed_tests}"
            echo "Sending notification with text: ${TEXT}"
            curl -X POST "https://api.telegram.org/bot7034452771:AAGAEMKO3shKsPOu1FlSJxmJkQ2SUIbLYHE/sendMessage" -H "Content-Type: application/json" --data '{"chat_id":"'"-4162914238"'", "text": "'"${TEXT}"'"}'
          else
            TEXT="Все тесты пройдены успешно!"
            echo "Sending notification with text: ${TEXT}"
            curl -X POST "https://api.telegram.org/bot7034452771:AAGAEMKO3shKsPOu1FlSJxmJkQ2SUIbLYHE/sendMessage" -H "Content-Type: application/json" --data '{"chat_id":"'"-4162914238"'", "text": "'"${TEXT}"'"}'
          fi


