name: Run tests
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-selenium
    - name: Run tests
      run: pytest tests/test_header_links.py::test_msk_header_projects




