name: Тестовый запуск
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Prepare config
        run: |
          cat <<EOT > connection_config.ini
          [testit]
          url = http://172.16.251.133
          privateToken = ${{ secrets.TMS_PRIVATE_TOKEN }}
          projectId = eefe44b2-3347-4e63-83e6-18614e869fe3
          configurationId = 659d9644-c5dc-4542-8aef-3858f219f8b6
          testRunId =
          testRunName = Test
          adapterMode = 2
          EOT
      - name: Test run for testit
        id: run_tests
        run: |
          pytest tests/test_login_broker.py --testit | tail -n 1
      - name: Notify on Telegram
        if: always()
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TEST_OUTPUT: ${{ steps.run_tests.outputs.stdout }}
        run: |
          TEST_OUTPUT="${{ env.TEST_OUTPUT }}"
          
          TEXT="Результаты тестирования: ${TEST_OUTPUT}"

          curl -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" -H "Content-Type: application/json" --data '{"chat_id":"'"${TELEGRAM_CHAT_ID}"'", "text": "'"${TEXT}"'"}'

