name: Тестовый запуск брокер
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Prepare config
        run: |
          # Ваши действия по подготовке конфигурации

      - name: Run tests with pytest and generate JSON report
        run: |
          pytest tests/test_broker.py --json-report -o json_report_file=report.json

      - name: Extract failed tests names
        id: failed_tests
        run: |
          jq -r '.tests[] | select(.outcome == "failed") | .nodeid' report.json | paste -sd "," - > failed_tests.txt
          if [[ -s failed_tests.txt ]]; then
            echo "::set-output name=names::$(<failed_tests.txt)"
          else
            echo "::set-output name=names::No failed tests"
          fi

      - name: Notify on Telegram
        if: always()
        env:
          TELEGRAM_BOT_TOKEN: 7034452771:AAGAEMKO3shKsPOu1FlSJxmJkQ2SUIbLYHE
          TELEGRAM_CHAT_ID: -4162914238
        run: |
          FAILED_TESTS="${{ steps.failed_tests.outputs.names }}"
          if [ "$FAILED_TESTS" != "No failed tests" ]; then
            TEXT="Упавшие тесты: ${FAILED_TESTS}"
          else
            TEXT="Все тесты прошли успешно!"
          fi
          curl -X POST "https://api.telegram.org/bot7034452771:AAGAEMKO3shKsPOu1FlSJxmJkQ2SUIbLYHE/sendMessage" -H "Content-Type: application/json" --data '{"chat_id":"'"-4162914238"'", "text": "'"${TEXT}"'"}'


