name: Тестовый запуск брокер
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Prepare config
        run: |
          cat > connection_config.ini <<EOT
          [testit]
          url = https://testit.itstrana.site/
          privateToken = ${{ secrets.TMS_PRIVATE_TOKEN }}
          projectId = eefe44b2-3347-4e63-83e6-18614e869fe3
          configurationId = 659d9644-c5dc-4542-8aef-3858f219f8b6
          testRunId =
          testRunName = Test
          adapterMode = 2
          EOT

      - name: Run tests with pytest and generate JSON report
        run: |
          pytest tests/test_broker.py --json-report -o json_report_file=report.json

      - name: Extract failed tests names
        id: failed_tests_extractor
        run: |
          FAILED_TESTS=$(jq -r '.tests[] | select(.outcome == "failed") | .nodeid' report.json | paste -sd "," -)
          echo "FAILED_TESTS=${FAILED_TESTS}" >> $GITHUB_ENV

      - name: Notify on Telegram if any tests failed
        if: env.FAILED_TESTS
        run: |
          TEXT="Упавшие тесты: $FAILED_TESTS"
          curl -X POST "https://api.telegram.org/bot7034452771:AAGAEMKO3shKsPOu1FlSJxmJkQ2SUIbLYHE/sendMessage" -H "Content-Type: application/json" --data '{"chat_id":"'"-4162914238"'", "text": "'"${TEXT}"'"}'

      - name: Notify on Telegram if all tests passed
        if: ${{ env.FAILED_TESTS == '' }}
        run: |
          TEXT="Все тесты прошли успешно!"
          curl -X POST "https://api.telegram.org/bot7034452771:AAGAEMKO3shKsPOu1FlSJxmJkQ2SUIbLYHE/sendMessage" -H "Content-Type: application/json" --data '{"chat_id":"'"-4162914238"'", "text": "'"${TEXT}"'"}'
