name: Тестовый запуск
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests with Allure
        run: pytest --alluredir=allure-results tests/test_header_links.py::test_msk_header_projects
        continue-on-error: true
      - name: Generate Allure report
        env:
          PATH: ${{ github.workspace }}/allure/allure-2.13.8/bin:$PATH
        run: allure generate allure-results --clean -o allure-report
      - name: Archive Allure report
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: allure-report/












